// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://glpseuldzplqffeuwwyy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdscHNldWxkenBscWZmZXV3d3l5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3ODMzMzIsImV4cCI6MjA3NDM1OTMzMn0.bzZAGbO1aKWbEw1zxspxfvqvBMqDFJrj3pUT_DheWko";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});